--------------------------------info[11:19:16]--------------------------------
System.Exception: v2rayN start up | v2rayN - V4.23 - 2021/10/16 | D:\2021soft\v2备用\v2rayN-Core\v2rayN.exe

 
--------------------------------未能找到文件“D:\2021soft\v2备用\v2rayN-Core\guiNConfig.json”。[11:19:16]--------------------------------
System.IO.FileNotFoundException: 未能找到文件“D:\2021soft\v2备用\v2rayN-Core\guiNConfig.json”。
文件名:“D:\2021soft\v2备用\v2rayN-Core\guiNConfig.json”
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path)
   在 v2rayN.Utils.LoadResource(String res)

 
--------------------------------info[11:19:17]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:19:54]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:19:55]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:20:01]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------无法连接到远程服务器[11:20:07]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10912
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:20:17]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:20:19]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------无法连接到远程服务器[11:20:20]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10913
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------无法连接到远程服务器[11:20:32]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10914
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------无法连接到远程服务器[11:20:44]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10915
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:20:49]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------无法连接到远程服务器[11:20:56]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10916
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------无法连接到远程服务器[11:21:08]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10917
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:21:17]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------无法连接到远程服务器[11:21:20]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10918
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------无法连接到远程服务器[11:21:32]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10919
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------无法连接到远程服务器[11:21:44]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10920
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:21:46]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------无法连接到远程服务器[11:21:56]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10921
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------无法连接到远程服务器[11:22:08]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10922
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:22:17]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------无法连接到远程服务器[11:22:20]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10923
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------2021/10/27 11:22:28 Using default config:  D:\2021soft\v2澶囩敤\v2rayN-Core\config.json
panic: Calling Domain() on an IPv4Address.

goroutine 1 [running]:
github.com/v2fly/v2ray-core/v4/common/net.ipv4Address.Domain(...)
	github.com/v2fly/v2ray-core/v4/common/net/address.go:132
github.com/v2fly/v2ray-core/v4/transport/internet/tcp.ListenTCP({0xe2d448, 0x1341e088}, {0xe2df28, 0x13a92e44}, 0x0, 0x13877c80, 0x13a943f8)
	github.com/v2fly/v2ray-core/v4/transport/internet/tcp/hub.go:46 +0x126
github.com/v2fly/v2ray-core/v4/transport/internet.ListenTCP({0xe2d448, 0x1341e088}, {0xe2df28, 0x13a92e44}, 0x0, 0x13877c80, 0x13a943f8)
	github.com/v2fly/v2ray-core/v4/transport/internet/tcp_hub.go:72 +0x24a
github.com/v2fly/v2ray-core/v4/app/proxyman/inbound.(*tcpWorker).Start(0x1a97ccd0)
	github.com/v2fly/v2ray-core/v4/app/proxyman/inbound/worker.go:115 +0x9b
github.com/v2fly/v2ray-core/v4/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0x14483180)
	github.com/v2fly/v2ray-core/v4/app/proxyman/inbound/always.go:153 +0x52
github.com/v2fly/v2ray-core/v4/app/proxyman/inbound.(*Manager).Start(0x1a924150)
	github.com/v2fly/v2ray-core/v4/app/proxyman/inbound/inbound.go:97 +0xbb
github.com/v2fly/v2ray-core/v4.(*Instance).Start(0x1a924090)
	github.com/v2fly/v2ray-core/v4/v2ray.go:338 +0x9d
main.main()
	github.com/v2fly/v2ray-core/v4/main/main.go:151 +0x18d
[11:22:29]--------------------------------
System.Exception: 2021/10/27 11:22:28 Using default config:  D:\2021soft\v2澶囩敤\v2rayN-Core\config.json
panic: Calling Domain() on an IPv4Address.

goroutine 1 [running]:
github.com/v2fly/v2ray-core/v4/common/net.ipv4Address.Domain(...)
	github.com/v2fly/v2ray-core/v4/common/net/address.go:132
github.com/v2fly/v2ray-core/v4/transport/internet/tcp.ListenTCP({0xe2d448, 0x1341e088}, {0xe2df28, 0x13a92e44}, 0x0, 0x13877c80, 0x13a943f8)
	github.com/v2fly/v2ray-core/v4/transport/internet/tcp/hub.go:46 +0x126
github.com/v2fly/v2ray-core/v4/transport/internet.ListenTCP({0xe2d448, 0x1341e088}, {0xe2df28, 0x13a92e44}, 0x0, 0x13877c80, 0x13a943f8)
	github.com/v2fly/v2ray-core/v4/transport/internet/tcp_hub.go:72 +0x24a
github.com/v2fly/v2ray-core/v4/app/proxyman/inbound.(*tcpWorker).Start(0x1a97ccd0)
	github.com/v2fly/v2ray-core/v4/app/proxyman/inbound/worker.go:115 +0x9b
github.com/v2fly/v2ray-core/v4/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0x14483180)
	github.com/v2fly/v2ray-core/v4/app/proxyman/inbound/always.go:153 +0x52
github.com/v2fly/v2ray-core/v4/app/proxyman/inbound.(*Manager).Start(0x1a924150)
	github.com/v2fly/v2ray-core/v4/app/proxyman/inbound/inbound.go:97 +0xbb
github.com/v2fly/v2ray-core/v4.(*Instance).Start(0x1a924090)
	github.com/v2fly/v2ray-core/v4/v2ray.go:338 +0x9d
main.main()
	github.com/v2fly/v2ray-core/v4/main/main.go:151 +0x18d

   在 v2rayN.Handler.V2rayHandler.V2rayStart()

 
--------------------------------无法连接到远程服务器[11:22:32]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10924
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------无法连接到远程服务器[11:22:44]--------------------------------
System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:10925
   在 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------进程已退出，因此无法获得所请求的信息。[11:22:46]--------------------------------
System.InvalidOperationException: 进程已退出，因此无法获得所请求的信息。
   在 System.Diagnostics.Process.EnsureState(State state)
   在 System.Diagnostics.Process.get_MainWindowHandle()
   在 System.Diagnostics.Process.CloseMainWindow()
   在 v2rayN.Handler.V2rayHandler.KillProcess(Process p)

 
--------------------------------info[11:23:41]--------------------------------
System.Exception: v2rayN start up | v2rayN - V4.23 - 2021/10/16 | D:\2021soft\v2rayN-Core423\v2rayN.exe

 
--------------------------------未能找到文件“D:\2021soft\v2rayN-Core423\StatisticLogOverall.json”。[11:23:42]--------------------------------
System.IO.FileNotFoundException: 未能找到文件“D:\2021soft\v2rayN-Core423\StatisticLogOverall.json”。
文件名:“D:\2021soft\v2rayN-Core423\StatisticLogOverall.json”
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path)
   在 v2rayN.Utils.LoadResource(String res)

 
--------------------------------info[11:23:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:23:43]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[11:24:37]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:24:38]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:24:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:24:51]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:25:02]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:25:14]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:25:26]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:25:38]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:25:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:25:44]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:25:50]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:25:58]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[11:26:09]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[11:26:28]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[11:26:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:27:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:28:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:29:05]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[11:29:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:30:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:31:27]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[11:31:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:32:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:33:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:34:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:35:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:36:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:37:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:38:29]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:38:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:39:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:40:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------远程服务器返回错误: (503) 服务器不可用。[11:41:21]--------------------------------
System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 v2rayN.Handler.DownloadHandle.ws_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

 
--------------------------------info[11:41:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:42:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:43:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:44:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:45:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:46:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:47:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:48:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:49:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:50:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:51:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:52:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:53:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:54:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:55:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:56:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:57:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:58:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[11:59:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:00:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:01:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:02:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:03:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:04:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:05:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:06:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:07:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:08:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:09:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:10:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:11:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:12:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:13:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:14:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:15:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:16:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:17:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:18:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:19:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:20:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:21:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:22:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:23:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:24:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:25:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:26:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:27:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:28:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:29:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:30:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:31:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:32:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:33:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:34:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:35:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:36:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:37:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:38:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:39:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:40:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:41:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:42:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:43:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:44:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:45:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:46:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:47:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:48:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:49:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:50:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:51:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:52:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:53:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:54:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:55:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:56:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:57:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:58:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[12:59:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:00:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:01:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:02:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:03:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:04:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:05:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:06:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:07:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:08:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:09:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:10:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:11:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:12:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:13:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:14:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:15:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:16:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:17:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:18:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:19:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:20:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:21:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:22:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:23:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:24:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:25:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:26:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:27:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:28:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:29:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:30:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:31:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:32:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:33:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:34:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:35:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:36:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:37:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:38:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:39:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:40:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:41:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:42:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:43:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:44:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:45:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:46:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:47:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:48:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:49:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:50:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:51:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:52:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:53:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:54:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:55:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:56:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:57:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:58:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[13:59:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:00:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:01:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:02:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:03:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:04:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:05:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:06:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:07:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:08:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:09:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:10:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:11:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:12:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:13:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:14:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:15:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:16:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:17:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:18:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:19:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:20:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:21:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:22:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:23:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:24:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:25:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:26:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:27:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:28:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:29:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:30:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:30:55]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:31:08]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:31:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:32:33]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:32:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:33:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:34:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:34:46]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:35:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:36:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:37:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:38:39]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:38:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:38:57]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:39:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:40:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:40:53]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:41:01]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:41:16]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:41:42]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:41:45]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:56:24]--------------------------------
System.Exception: v2rayN start up | v2rayN - V4.23 - 2021/10/16 | D:\2021soft\v2rayN-Core423\v2rayN.exe

 
--------------------------------info[14:56:24]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:56:25]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:57:19]--------------------------------
System.Exception: Failed to call AssignProcessToJobObject! GetLastError=5

 
--------------------------------info[14:57:24]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------未将对象引用设置到对象的实例。[14:57:55]--------------------------------
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 v2rayN.Utils.List2String(List`1 lst, Boolean wrap)

 
--------------------------------未将对象引用设置到对象的实例。[14:57:55]--------------------------------
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 v2rayN.Utils.List2String(List`1 lst, Boolean wrap)

 
--------------------------------未将对象引用设置到对象的实例。[14:57:55]--------------------------------
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 v2rayN.Utils.List2String(List`1 lst, Boolean wrap)

 
--------------------------------info[14:58:24]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[14:59:24]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[15:00:24]--------------------------------
System.Exception: UpdateTaskRun

 
--------------------------------info[15:01:24]--------------------------------
System.Exception: UpdateTaskRun

 
